//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferNu65.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PR-2\\PR2SQL2017")]
        public string SqlServerNu65 {
            get {
                return ((string)(this["SqlServerNu65"]));
            }
            set {
                this["SqlServerNu65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nu65DB")]
        public string SqlDbNu65Db {
            get {
                return ((string)(this["SqlDbNu65Db"]));
            }
            set {
                this["SqlDbNu65Db"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string TimeoutSqlServerConnectInSecond {
            get {
                return ((string)(this["TimeoutSqlServerConnectInSecond"]));
            }
            set {
                this["TimeoutSqlServerConnectInSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\VirtualMashinFiles\\nu65\\DBF\\V\\FOX60\\arm\\base\\")]
        public string FoxproDbFolder_Fox60_Arm_Base {
            get {
                return ((string)(this["FoxproDbFolder_Fox60_Arm_Base"]));
            }
            set {
                this["FoxproDbFolder_Fox60_Arm_Base"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\VirtualMashinFiles\\nu65\\DBF\\")]
        public string FoxproDbFolder_nu65 {
            get {
                return ((string)(this["FoxproDbFolder_nu65"]));
            }
            set {
                this["FoxproDbFolder_nu65"] = value;
            }
        }
    }
}
